"""empty message

Revision ID: 150e03eaa460
Revises: fd0f2222b033
Create Date: 2024-01-09 14:46:08.696990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150e03eaa460'
down_revision = 'fd0f2222b033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravatar_hash', sa.String(length=32), nullable=True))
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('gravatar_hash')

    # ### end Alembic commands ###
